spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    hibernate:
      ddl-auto: validate

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

